### ISSUE TITLE
Homebridge crashing

### ISSUE THREAD

**Issue by sifield** [SphtKr/homebridge-itunes#22]
Hi, This is causing homebridge to crash, any thoughts why, here are the errors:

[2/17/2017, 5:44:40 PM] Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:115
  var rtn = this.value.substring(this.index, end-1);
                       ^

TypeError: this.value.substring is not a function
    at Object.exports.UndefinedParser (/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:115:24)
    at Object.parseFromFirstRemaining (/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:44:34)
    at Object.exports.parse (/usr/local/lib/node_modules/homebridge-itunes/node_modules/applescript/lib/applescript-parser.js:10:37)
    at ITunesPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/index.js:443:31)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:49:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)

thanks

**Comment by SphtKr** [comment]
I've just published 0.2.0-alpha0, which I hope may fix your issue. Can you try it:

    npm install -g homebridge-itunes@latest

And let me know if it helps, please? Thanks!

**Comment by SphtKr** [comment]
Whoops...and see the [important upgrade notice](https://github.com/SphtKr/homebridge-itunes#important-upgrade-notice)!

**Comment by SphtKr** [comment]
Likewise, 0.2.0-alpha1 is now out, and it makes the mentioned upgrade notice unnecessary.
