### ISSUE TITLE
Using the iTunes plug-in, Homebridge crashing

### ISSUE THREAD

**Issue by Guoer-xz** [SphtKr/homebridge-itunes#27]
Once you click on the iTunes button, homebridge will terminate the service, repeated several times the same results, but do not use iTunes related buttons, homebridge work is normal,help

---------------------------------------------------------------------

/usr/local/lib/node_modules/homebridge-itunes/index.js:578
      .updateValue("");
      ^

TypeError: Cannot read property 'updateValue' of undefined
    at ITunesPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/index.js:578:7)
    at /usr/local/lib/node_modules/homebridge-itunes/index.js:60:33
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:49:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by SphtKr** [comment]
See the update note on [README.md](/sphtkr/homebridge-itunes), you need to delete or move your cachedAccessories file.

**Comment by SphtKr** [comment]
And/or, update to 0.2.0-alpha1, which should handle the upgrade of cached accessories more gracefully now.
