### ISSUE TITLE
Cannot read property 'updateValue' of undefined

### ISSUE THREAD

**Issue by martinorob** [SphtKr/homebridge-itunes#30]
/usr/local/lib/node_modules/homebridge-itunes/index.js:557
      .updateValue(rtn[1]);
      ^

TypeError: Cannot read property 'updateValue' of undefined
    at ITunesPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/index.js:557:7)
    at /usr/local/lib/node_modules/homebridge-itunes/index.js:60:33
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:49:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

**Comment by SphtKr** [comment]
I've just published 0.2.0-alpha1, which should fix your issue. You could also fix it by manually removing `~/.homebridge/accessories/cachedAccessories`, but updating to alpha1 is the best solution. Can you try this and let me know if it resolves the problem?

**Comment by martinorob** [comment]
0.2.0-alpha1 working but sometimes give that error.. (and then I have to delete chacedaccessories file..)
