### ISSUE TITLE
Can't connect to iTunes?

### ISSUE THREAD

**Issue by APPS2CREATE** [SphtKr/homebridge-itunes#41]
I've just installed homebridge and wanted to test it with itunes. 
So i installed homebridge-itunes and added the platform to the config file. 
![screen shot 2017-04-20 at 13 04 45](https://cloud.githubusercontent.com/assets/16364000/25227789/337a10dc-25ca-11e7-8c15-900f3625f5be.png)

but i'm always getting this error: 
![screen shot 2017-04-20 at 13 04 32](https://cloud.githubusercontent.com/assets/16364000/25227798/3daf78bc-25ca-11e7-98ed-b5a423309279.png)

How can i fix this?

Thx!

**Comment by SphtKr** [comment]
Wow, this is one I haven't seen before. Good news/bad news, early research suggests you may have a problem with your macOS installation, believe it or not...but seems there's a pretty safe and easy fix, even if it doesn't sound like it.

Try the troubleshooting steps here: https://discussions.agilebits.com/discussion/64048/the-operation-couldnt-be-completed-osascript-cannot-open-default-scripting-component and if you get the same results, you probably have the same problem and need the same solution.

**Comment by jelvs** [comment]
Hey, I have one question does it work for Windows, or only for OSX? Thks keep up with the good work :)

**Comment by badrabbit** [comment]
I'm getting the same errors. Tried everything from your suggestion above but even after a reinstall of macOS Sierra, the errors still remain:
`[2017-6-18 15:31:46] [Homebridge Server] is listening on: http://10.0.1.10:8765
[2017-6-18 15:31:46] Homebridge is running on port 51826.
[2017-6-18 15:31:48] Error: 34:42: execution error: „iTunes“ hat einen Fehler erhalten: „selected of AirPlay device id 11725“ kann nicht gelesen werden. (-1728)

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:39:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[2017-6-18 15:31:48] Error: 34:46: execution error: „iTunes“ hat einen Fehler erhalten: „sound volume of AirPlay device id 11725“ kann nicht gelesen werden. (-1728)

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:39:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[2017-6-18 15:31:48] Error: 34:42: execution error: „iTunes“ hat einen Fehler erhalten: „selected of AirPlay device id 11722“ kann nicht gelesen werden. (-1728)

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:39:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[2017-6-18 15:31:48] Error: 34:46: execution error: „iTunes“ hat einen Fehler erhalten: „sound volume of AirPlay device id 11722“ kann nicht gelesen werden. (-1728)

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:39:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[2017-6-18 15:31:49] Error: 34:42: execution error: „iTunes“ hat einen Fehler erhalten: „selected of AirPlay device id 11723“ kann nicht gelesen werden. (-1728)

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:39:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[2017-6-18 15:31:49] Error: 34:46: execution error: „iTunes“ hat einen Fehler erhalten: „sound volume of AirPlay device id 11723“ kann nicht gelesen werden. (-1728)

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-itunes/node_modules/node-osascript/lib/index.js:39:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
`
